name: devtest
channels:
  - conda-forge
  - defaults
dependencies:
  # jupyterhub-singleuser version 3 or greater is a requirement for working well
  # with a JupyterHub such as at https://linkedearth.2i2c.cloud. After
  # https://github.com/jupyterhub/repo2docker/pull/1239 is merged, this doesn't
  # need to be specified.
  #
  - jupyterhub-singleuser>=3.0
  - cartopy
  - pip
  - python
  - libstdcxx-ng
  - numpy
  - netcdf4
  - aiohttp
  - zarr
  - fsspec
  - requests
  - xarray
  - cftime
  - dask
  - jupyter
  - jupyterlab_templates
  - pip:
    - setuptools
    - pyleoclim
    - nc-time-axis
    - ipympl

